export const ACTION_GET_USER_AUTHORIZATION_STATUS="ACTION_GET_USER_AUTHORIZATION_STATUS";
export const ACTION_GET_USER_DETAILS="ACTION_GET_USER_DETAILS";
export const ACTION_LOGOUT_USER="ACTION_LOGOUT_USER";
export const ACTION_CREATE_NEW_USER="ACTION_CREATE_NEW_USER";
export const ACTION_GET_ALL_BOOKS="ACTION_GET_ALL_BOOKS";
export const ACTION_GET_BOOKS_IN_CART="ACTION_GET_BOOKS_IN_CART";
export const ACTION_GET_BOOKS_IN_SHELF="ACTION_GET_BOOKS_IN_SHELF";

export const NOTIFY_AJAX_CALL_STARTS="NOTIFY_AJAX_CALL_START";
export const NOTIFY_AJAX_CALL_SUCCESS="NOTIFY_AJAX_CALL_SUCCESS";
export const NOTIFY_AJAX_CALL_FAILURE="NOTIFY_AJAX_CALL_FAILURE";